global:
    resolve_timeout: 5m
route:
    repeat_interval: 5m
    receiver: default
    routes:
      - receiver: "telegram"
        group_wait: 10s
        match_re:
          alertname: ".*"

receivers:
    - name: "default"
    - name: 'telegram'
      webhook_configs:
      - send_resolved: True
        url: ''